[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-bugbear without opinionated rules
    "B0",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
]
[tool.ruff.lint.extend-per-file-ignores]
"*/migrations/*" = ["E501"]
"*/tests/*" = ["E501"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "geo_search.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = [
    # Ignore whitenoise warning about static directory not existing during tests
    "ignore:No directory at:UserWarning:whitenoise.base",
    # Ignore cache key warnings during testing
    "ignore:Cache key contains characters that will cause errors if used with memcached:RuntimeWarning:django",
    # Ignore deprecation warning from gisserver until it has been fixed upstream
    "ignore:The django.utils.timezone.utc alias is deprecated",
]
