# Generated by Django 3.2.7 on 2021-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_municipality_default_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="post_office",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
