# Generated by Django 3.2.12 on 2022-03-07 09:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_address_post_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCodeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Postal code areas",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={"verbose_name_plural": "Municipalities"},
        ),
        migrations.RemoveField(
            model_name="address",
            name="post_office",
        ),
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="municipality",
            name="code",
            field=models.CharField(default="", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="postal_code_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="address.postalcodearea",
            ),
        ),
        migrations.CreateModel(
            name="PostalCodeAreaTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="address.postalcodearea",
                    ),
                ),
            ],
            options={
                "verbose_name": "postal code area Translation",
                "db_table": "address_postalcodearea_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
