# Generated by Django 5.0.8 on 2024-08-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_municipality_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="postalcodearea",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.municipality",
            ),
        ),
    ]
