# Generated by Django 6.0 on 2026-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0007_postalcodearea_municipality"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["municipality", "id"],
                include=(
                    "street",
                    "number",
                    "number_end",
                    "letter",
                    "postal_code_area",
                    "location",
                    "modified_at",
                ),
                name="idx_address_municipality_id",
            ),
        ),
    ]
