# Generated by Django 6.0.2 on 2026-02-16 10:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_address_idx_address_municipality_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.AlterModelOptions(
            name="municipalitytranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Municipality Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="postalcodearea",
            options={
                "verbose_name": "Postal code area",
                "verbose_name_plural": "Postal code areas",
            },
        ),
        migrations.AlterModelOptions(
            name="postalcodeareatranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Postal code area Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="street",
            options={"verbose_name": "Street", "verbose_name_plural": "Streets"},
        ),
        migrations.AlterModelOptions(
            name="streettranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Street Translation",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="letter",
            field=models.CharField(blank=True, max_length=2, verbose_name="Letter"),
        ),
        migrations.AlterField(
            model_name="address",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="address.municipality",
                verbose_name="Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(blank=True, max_length=6, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="address",
            name="number_end",
            field=models.CharField(blank=True, max_length=6, verbose_name="Number end"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="address.postalcodearea",
                verbose_name="Postal code area",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="address.street",
                verbose_name="Street",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="code",
            field=models.CharField(max_length=3, verbose_name="Municipality code"),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="postalcodearea",
            name="area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="postalcodearea",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.municipality",
                verbose_name="Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="postalcodearea",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Postal code"
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="address.municipality",
                verbose_name="Municipality",
            ),
        ),
    ]
