# Generated by Django on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0009_update_model_verbose_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postalcodearea",
            name="municipality",
        ),
    ]
