# Generated by Django 6.0.2 on 2026-02-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0010_remove_postalcodearea_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="postalcodeareatranslation",
            name="post_office",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Post office"
            ),
        ),
    ]
