# Generated by Django 6.0.5 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0011_postalcodearea_post_office"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="municipalitytranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postalcodeareatranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="streettranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="municipalitytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="address_municipality_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="postalcodeareatranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="address_postalcodearea_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="streettranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="address_street_translation_uniq_lang",
            ),
        ),
    ]
